# Generated by Django 4.1.2 on 2022-10-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0004_alter_patient_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance_scheme',
            name='insurance',
        ),
    ]
