# Generated by Django 4.1.2 on 2022-10-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0010_worker_dob_worker_gender_worker_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='blood',
            field=models.CharField(choices=[('1', 'O-'), ('1', 'O+'), ('2', 'A+'), ('2', 'A-'), ('2', 'B+'), ('2', 'B-'), ('2', 'AB+'), ('2', 'AB-')], default='1', max_length=20),
        ),
    ]
