# Generated by Django 4.1.2 on 2022-10-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0012_jb_dob_jb_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='type',
            field=models.CharField(choices=[('1', 'Private'), ('2', 'Public')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='worker',
            name='blood',
            field=models.CharField(choices=[('1', 'O-'), ('1', 'O+'), ('3', 'A+'), ('4', 'A-'), ('5', 'B+'), ('6', 'B-'), ('7', 'AB+'), ('8', 'AB-')], default='1', max_length=20),
        ),
    ]
