# Generated by Django 4.1.2 on 2022-10-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0013_insurance_type_alter_worker_blood'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='registration_no',
            field=models.CharField(default='4', max_length=20),
            preserve_default=False,
        ),
    ]
