# Generated by Django 4.1.2 on 2022-10-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0014_insurance_registration_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='type',
        ),
        migrations.AddField(
            model_name='insurance',
            name='types',
            field=models.CharField(choices=[('1', 'Private'), ('2', 'Public')], default='1', max_length=20),
            preserve_default=False,
        ),
    ]
