# Generated by Django 4.1.2 on 2022-10-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MWMapp', '0015_remove_insurance_type_insurance_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='types',
            field=models.TextField(choices=[('1', 'Private'), ('2', 'Public')], default='1', max_length=20),
        ),
    ]
