# Generated by Django 4.1.2 on 2022-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MWMapp", "0017_insurance_name1"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="types",
            field=models.TextField(
                choices=[("Private", "Private"), ("Public", "Public")],
                default="Public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jb",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="1",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="blood",
            field=models.CharField(
                choices=[
                    ("o-", "O-"),
                    ("o+", "O+"),
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("Ab-", "AB-"),
                ],
                default="A+",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="worker",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female")],
                default="Male",
                max_length=20,
            ),
        ),
    ]
